In [3]:
import datetime as dt
import time as tm

In [4]:
tm.time()

1662602672.376821

In [5]:
dtnow = dt.datetime.fromtimestamp(tm.time())

In [6]:
dtnow

datetime.datetime(2022, 9, 7, 22, 5, 23, 722686)

## Object-Oriented Programming in Python: Objects and map()

In [7]:
class Person:
    department = "School of Information"
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In `class`, we need to use `self`. At this moment, we cannot see anything. However, the class exists, but we haven't created any objects yet.

In [9]:
person = Person()
person.set_name('Stella')
person.set_location('China')
print('{} comes from {}.'.format(person.name, person.location))

Stella comes from China.


`map(function, iterable, ...)`
- Return an iterator that applies function to every item of iterable, yielding the results.
- With multiple iterables, the iterator stops when the shortest iterable is exhausted.

In [11]:
store1 = [10.00, 11.00, 1.34, 2.34]
store2 = [9, 12,2,4]
cheapest = map(min, store1, store2)
cheapest

We can use `for loop` to print out results.

In [14]:
for i in cheapest:
    print(i)

9
11.0
1.34
2.34


### Lambda and List Comprehension
- condensed format

In [15]:
my_function = lambda a,b,c: a+b

In [17]:
my_function(1,2,6)

3

In [20]:
# list comprehension
my_list = []
for number in range(0,1000):
    if number % 2 == 0:
        my_list.append(number)
        
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [21]:
my_list = [number for number in range(0,1000) if number % 2 == 0]

In [22]:
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

### Numerical Python Library
- Array Creation

- We can print the number of dimensions of a list using `ndim` attribute, such as `a.ndim`,`b.shape`,`b.dtype`,`a.dtype.name`
- We can create a sequence of numebrs in an array with `arange()` function
- We can generate a list of floats with `linspace()` function
- We can apply aggregation functinos: `sum()`,`min()`,`max()`,`mean()`, such as `a.min()`
- We can create matrix: `np.arange(1,16,1).reshape(3,5)`

In [23]:
import numpy as np
import math

In [35]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(a)
a.dtype
a.dtype.name

[1 2 3]


'int64'

In [32]:
print(a.ndim)
print(b.ndim, b.shape)

1
2 (2, 3)


In [36]:
# create array with all 0
c = np.zeros((2,3))
# create array with all 1
d = np.ones((2,3))
print(c,d)

In [38]:
# create array with random numbers
np.random.rand(2,3)

array([[0.56538012, 0.66430521, 0.35805421],
       [0.2567746 , 0.32018025, 0.67092886]])

In [40]:
# create a list of values with start(inclusive) and end(exclusive), with intevals
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [41]:
# generate a list of floats with `linspace()` function, both values are inclusive
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

### Array Operations

In [42]:
# Arithmetic operators on array apply elementwise
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(a*b)
print(a+b)

[ 10  40  90 160]
[11 22 33 44]


In [43]:
farenheit = np.array([10,40,100])

# the formula for conversion: ((F-32)*5/9 = C)
celcius = (farenheit-32)*5/9
celcius

array([-12.22222222,   4.44444444,  37.77777778])

In [45]:
# use boolean array to check (True/False)
celcius > 0

array([False,  True,  True])

In [46]:
# Matrix Product with "@"
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[4,5,6]])
print(a*b)
print(a@b)

[[ 1  4  9]
 [ 4 10 18]
 [ 4 10 18]]
[21 27 33]


In [48]:
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

6
1
3
2.0


In [49]:
np.arange(1,16,1).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Indexing, Slicing and Iterating

In [53]:
a = np.array([1,3,4,5]).reshape(2,2)
a[1,1]

5

In [55]:
np.array([a[0,0], a[1,1]])

array([1, 5])

In [56]:
a = np.array([[1,2],[3,4],[5,6]])
# we can use "zips" to zip the first list and the second list up
print(a[[0,1,2],[0,1,1]])

[1 4 6]


### Boolean Indexing
- Select arbitrary elements based on conditions, i.e. `a[a>5]`

In [57]:
print(a>5)

[[False False]
 [False False]
 [False  True]]


In [58]:
print(a[a>5])

[6]


### Slicing
- Slicing is a way to create a sub-array based on the original array (with `:`)
- When we change some values with `slicing`, the original stuff will also change

In [60]:
a = np.arange(10)
a[:3]

array([0, 1, 2])